"""Minecraft Java Edition server handler.

Install/update by dropping a server jar into install_dir/server.jar. Users
provide the jar (either uploaded via the manager UI, or downloaded manually
from mojang.com / papermc.io / etc). We do NOT auto-download so we avoid
guessing which flavor (Vanilla, Paper, Fabric, Forge) the user wants.

The generated start.sh launches inside tmux so the console channel works
(see app/control.py console helpers).
"""
from __future__ import annotations

from pathlib import Path

from .base import TypeHandler


_START_TEMPLATE = """#!/usr/bin/env bash
# Generated by gamesrv manager — safe to hand-edit; will be regenerated on
# `install`/`update` unless you set MANAGED=false below.
# MANAGED=true
set -euo pipefail
cd "$(dirname "$0")"

SESSION="gs-{name}"
JAR="server.jar"

if [[ ! -f "$JAR" ]]; then
  echo "ERROR: $JAR not found in $(pwd). Upload one via the manager (area=install)." >&2
  exit 1
fi

# EULA is required by Mojang. Accept only if the operator has toggled it.
if [[ ! -f eula.txt ]]; then
  echo "eula=false" > eula.txt
fi

# tmux gives us a real stdin channel so 'send console command' works.
if ! command -v tmux >/dev/null; then
  echo "ERROR: tmux is required (apt install tmux)" >&2
  exit 1
fi

# Kill any stale detached session with the same name.
tmux kill-session -t "$SESSION" 2>/dev/null || true

# Launch inside tmux in the FOREGROUND so systemd sees the process.
# `new-session -A -d` would detach; we want systemd to track this PID.
exec tmux new-session -s "$SESSION" -n mc \\
  "java -Xms{xms}M -Xmx{xmx}M {extra_args} -jar $JAR nogui"
"""


_STOP_TEMPLATE = """#!/usr/bin/env bash
# Graceful stop: send 'stop' to the MC console via tmux, wait, then let
# systemd finish. Prevents world corruption.
set -euo pipefail
SESSION="gs-{name}"
if tmux has-session -t "$SESSION" 2>/dev/null; then
  tmux send-keys -t "$SESSION" "say Server stopping in 5s..." Enter || true
  sleep 5
  tmux send-keys -t "$SESSION" "stop" Enter || true
  # Wait up to 60s for Minecraft to exit.
  for _ in $(seq 1 60); do
    tmux has-session -t "$SESSION" 2>/dev/null || exit 0
    sleep 1
  done
fi
"""


class MinecraftJavaHandler(TypeHandler):
    def install(self) -> list[str]:
        self.ensure_dirs()
        msgs: list[str] = []

        # A little headroom for JVM overhead — Xms half of Xmx is a decent default.
        xmx = max(512, self.sd.memory_mb)
        xms = max(512, xmx // 2)

        start_sh = _START_TEMPLATE.format(
            name=self.sd.name,
            xmx=xmx,
            xms=xms,
            extra_args=self.sd.java_args,
        )
        stop_sh = _STOP_TEMPLATE.format(name=self.sd.name)

        self.write_script("start.sh", start_sh)
        self.write_script("stop.sh", stop_sh)
        msgs.append(f"wrote {self.install_dir/'start.sh'}")
        msgs.append(f"wrote {self.install_dir/'stop.sh'}")

        # server.env: pass Minecraft options as env vars if needed later.
        env_values = {"MC_MEMORY_MB": str(self.sd.memory_mb), "MC_PORT": str(self.sd.port)}
        env_values.update(self.sd.extra_env)
        self.write_env_file(env_values)
        msgs.append(f"wrote {self.install_dir/'server.env'}")

        # Symlink world into the install dir so Minecraft writes to the NFS bind mount.
        link = self.install_dir / "world"
        if not link.exists():
            link.symlink_to(self.world_dir)
            msgs.append(f"symlinked world -> {self.world_dir}")

        jar = self.install_dir / "server.jar"
        if not jar.exists():
            msgs.append("NOTE: upload server.jar (area=install, path=server.jar) before starting")

        return msgs

    def update(self) -> list[str]:
        # Minecraft updates = replace server.jar. Users upload the new jar and
        # then hit 'update' which just regenerates scripts (in case memory/args
        # changed) and confirms the jar is in place.
        msgs = self.install()
        jar = self.install_dir / "server.jar"
        if jar.exists():
            msgs.append(f"server.jar present ({jar.stat().st_size} bytes)")
        else:
            msgs.append("WARNING: server.jar still missing — upload it first")
        return msgs
