"""Minecraft Forge server handler (1.17+ layout — includes 1.20.1).

Modern Forge does NOT boot via `java -jar server.jar`. The installer produces
`run.sh` + `user_jvm_args.txt` + a Forge args file under `libraries/`. That
means the vanilla `minecraft-java` handler cannot start it — this one exists
specifically for the modded case.

What install() does:
  1. Ensure install_dir + world_dir + eula.txt exist.
  2. Symlink install_dir/world -> world_dir (saves live on TrueNAS).
  3. Write user_jvm_args.txt so Forge picks up -Xms/-Xmx from memory_mb.
     (Forge reads THIS file, not any -Xmx on the java command line.)
  4. Generate start.sh that launches `./run.sh nogui` inside tmux
     (foreground, so systemd tracks the PID and the Console tab works).
  5. Generate stop.sh that sends `stop` to the tmux session for a clean
     world-save — critical for modded worlds with custom dimensions.
  6. If a 1.20.x MC version is declared, warn (loudly) when the system java
     isn't Java 17. Forge 1.20.x will NOT run on Java 21.

What it does NOT do:
  - Auto-download the Forge installer. Users upload the whole server tree
    (mods/, config/, libraries/, run.sh, user_jvm_args.txt) via the Files
    tab or SFTP — this is intentional; it keeps the handler independent of
    which Forge build, which mod pack, and which curseforge/modrinth source
    the user prefers.
"""
from __future__ import annotations

import re
import shutil
import subprocess

from .base import TypeHandler


_START_TEMPLATE = """#!/usr/bin/env bash
# Generated by gamesrv manager for a Forge server. Runs Forge's own run.sh
# inside tmux so the manager can send console commands and perform a
# graceful stop (critical for modded worlds with custom dimensions).
set -euo pipefail
cd "$(dirname "$0")"

SESSION="gs-{name}"

if [[ ! -x "./run.sh" ]]; then
  if [[ -f "./run.sh" ]]; then
    chmod +x ./run.sh
  else
    echo "ERROR: run.sh not found in $(pwd). Upload the Forge server files first." >&2
    echo "       (Look for run.sh / user_jvm_args.txt from the Forge installer output.)" >&2
    exit 1
  fi
fi

# Forge still requires Mojang's EULA. If it's false, run.sh will exit; make
# sure eula.txt=true before starting (either via the Files tab or by hand).
if [[ ! -f eula.txt ]]; then
  echo "eula=false" > eula.txt
fi

if ! command -v tmux >/dev/null; then
  echo "ERROR: tmux is required (apt install tmux)" >&2
  exit 1
fi

tmux kill-session -t "$SESSION" 2>/dev/null || true

# Foreground tmux so systemd tracks the PID. tmux new-session (without -d)
# needs a PTY, which systemd doesn't give us. script(1) from util-linux
# allocates one for us and forwards the exit code of the wrapped command.
#   -q  quiet (no "Script started, output log file ...")
#   -e  exit with the child's exit code
#   -f  flush after each write
#   -c  command
exec script -qefc "tmux new-session -s '$SESSION' -n forge './run.sh nogui'" /dev/null
"""


_STOP_TEMPLATE = """#!/usr/bin/env bash
# Graceful stop: send 'stop' to the Forge console via tmux, then wait for
# the JVM to exit. Modded packs (Deeper Darker etc.) can take a while to
# flush all custom dimensions — allow up to 120s before systemd hard-kills.
set -euo pipefail
SESSION="gs-{name}"
if tmux has-session -t "$SESSION" 2>/dev/null; then
  tmux send-keys -t "$SESSION" "say Server stopping in 10s..." Enter || true
  sleep 10
  tmux send-keys -t "$SESSION" "stop" Enter || true
  for _ in $(seq 1 120); do
    tmux has-session -t "$SESSION" 2>/dev/null || exit 0
    sleep 1
  done
fi
"""


def _java_major_version() -> int | None:
    """Best-effort parse of `java -version`. Returns e.g. 17, 21, or None."""
    java = shutil.which("java")
    if not java:
        return None
    try:
        r = subprocess.run([java, "-version"], capture_output=True, text=True, timeout=5)
    except (OSError, subprocess.TimeoutExpired):
        return None
    m = re.search(r'version "(\d+)', (r.stderr or r.stdout))
    if not m:
        return None
    try:
        return int(m.group(1))
    except ValueError:
        return None


# Mojang's Java requirements per MC version family. We only need enough to
# warn on obviously-wrong combos.
_MC_JAVA_REQ = {
    "1.16": 8,
    "1.17": 16,
    "1.18": 17,
    "1.19": 17,
    "1.20": 17,   # Forge 1.20.x MUST run on Java 17, NOT 21
    "1.21": 21,
}


def _required_java(mc_version: str | None) -> int | None:
    if not mc_version:
        return None
    for prefix, req in _MC_JAVA_REQ.items():
        if mc_version.startswith(prefix):
            return req
    return None


class MinecraftForgeHandler(TypeHandler):
    def install(self) -> list[str]:
        self.ensure_dirs()
        msgs: list[str] = []

        # 1. user_jvm_args.txt — Forge reads this instead of -Xmx on argv.
        xmx = max(1024, self.sd.memory_mb)
        xms = max(1024, xmx // 2)
        user_args = self.install_dir / "user_jvm_args.txt"
        # Regenerate every install so memory_mb changes actually take effect.
        # Leave a header so hand-edits by the user get overwritten with a
        # visible reason.
        user_args.write_text(
            "# Managed by gamesrv (regenerated on Install/Update).\n"
            f"# Source: server definition memory_mb={self.sd.memory_mb}\n"
            f"-Xms{xms}M\n-Xmx{xmx}M\n"
            + (self.sd.java_args.strip() + "\n" if self.sd.java_args.strip() else ""),
            encoding="utf-8",
        )
        msgs.append(f"wrote {user_args} (-Xms{xms}M -Xmx{xmx}M)")

        # 2. Launcher scripts.
        self.write_script("start.sh", _START_TEMPLATE.format(name=self.sd.name))
        self.write_script("stop.sh", _STOP_TEMPLATE.format(name=self.sd.name))
        msgs.append(f"wrote {self.install_dir/'start.sh'} + stop.sh")

        # 3. server.env (informational for the unit).
        env_values = {
            "MC_MEMORY_MB": str(self.sd.memory_mb),
            "MC_PORT": str(self.sd.port),
        }
        if self.sd.mc_version:
            env_values["MC_VERSION"] = self.sd.mc_version
        if self.sd.forge_version:
            env_values["FORGE_VERSION"] = self.sd.forge_version
        env_values.update(self.sd.extra_env)
        self.write_env_file(env_values)
        msgs.append(f"wrote {self.install_dir/'server.env'}")

        # 4. Symlink world -> TrueNAS bind mount.
        link = self.install_dir / "world"
        if not link.exists():
            link.symlink_to(self.world_dir)
            msgs.append(f"symlinked world -> {self.world_dir}")

        # 5. EULA reminder — do NOT auto-accept for the user.
        eula = self.install_dir / "eula.txt"
        if not eula.exists() or "eula=true" not in eula.read_text(encoding="utf-8", errors="ignore"):
            msgs.append("NOTE: eula.txt is not set to true — Forge will exit on first start.")
            msgs.append("      Accept Mojang's EULA (edit install_dir/eula.txt: eula=true) before starting.")

        # 6. run.sh presence + java version sanity check.
        run_sh = self.install_dir / "run.sh"
        if not run_sh.exists():
            msgs.append("NOTE: run.sh is missing — upload the Forge server tree (mods/, config/,")
            msgs.append("      libraries/, run.sh, user_jvm_args.txt) via the Files tab or SFTP.")
            msgs.append("      If you only have run.bat, use scripts/convert_bat_to_sh.py to generate one.")

        required = _required_java(self.sd.mc_version)
        found = _java_major_version()
        if required is not None:
            if found is None:
                msgs.append(f"WARNING: could not detect installed java — Forge {self.sd.mc_version} needs Java {required}.")
            elif found != required:
                msgs.append(
                    f"WARNING: system java is {found}, but Minecraft {self.sd.mc_version} Forge requires Java {required}. "
                    f"Install openjdk-{required}-jre-headless and ensure it is the default `java`."
                )
            else:
                msgs.append(f"java {found} matches required {required} for MC {self.sd.mc_version} ✓")

        return msgs

    def update(self) -> list[str]:
        # For Forge, "update the game software" = the operator uploads a new
        # Forge installer output (or swaps mod jars in mods/) via the Files
        # tab and we regenerate the launcher scripts. There's no reliable
        # single-URL auto-update for a modded pack.
        msgs = ["Forge updates are manual — upload new Forge tree and/or mod jars via the Files tab,"]
        msgs.append("then click Update again. Regenerating launcher scripts + user_jvm_args.txt now...")
        msgs.extend(self.install())
        return msgs
