"""Minecraft Java Edition server handler.

Install/update by dropping a server jar into install_dir/server.jar. Users
provide the jar (either uploaded via the manager UI, or downloaded manually
from mojang.com / papermc.io / etc). We do NOT auto-download so we avoid
guessing which flavor (Vanilla, Paper, Fabric, Forge) the user wants.

The generated start.sh launches inside tmux so the console channel works
(see app/control.py console helpers).
"""
from __future__ import annotations

from pathlib import Path

from .base import TypeHandler, resolve_stop_timeout


_START_TEMPLATE = """#!/usr/bin/env bash
# Generated by gamesrv manager — safe to hand-edit; will be regenerated on
# `install`/`update` unless you set MANAGED=false below.
# MANAGED=true
set -euo pipefail
cd "$(dirname "$0")"

SESSION="gs-{name}"
JAR="server.jar"

if [[ ! -f "$JAR" ]]; then
  echo "ERROR: $JAR not found in $(pwd). Upload one via the manager (area=install)." >&2
  exit 1
fi

# EULA is required by Mojang. Accept only if the operator has toggled it.
if [[ ! -f eula.txt ]]; then
  echo "eula=false" > eula.txt
fi

# tmux gives us a real stdin channel so 'send console command' works.
if ! command -v tmux >/dev/null; then
  echo "ERROR: tmux is required (apt install tmux)" >&2
  exit 1
fi

# systemd runs us without a controlling terminal and often with TERM unset.
# Older tmux (<3.3) prints "open terminal failed: not a terminal" and exits
# 1 in that case even with -d. Setting a known-good TERM and using -f
# /dev/null (so tmux doesn't try to source a user config that references a
# terminal) avoids that failure mode.
export TERM="${{TERM:-screen-256color}}"
TMUX="tmux -f /dev/null"

# Kill any stale detached session with the same name.
$TMUX kill-session -t "$SESSION" 2>/dev/null || true

# Start tmux DETACHED (no PTY needed under systemd), then block until the
# session ends. See minecraft_forge.py for the design rationale.
$TMUX new-session -d -s "$SESSION" -n mc "java -Xms{xms}M -Xmx{xmx}M {extra_args} -jar $JAR nogui"
while $TMUX has-session -t "$SESSION" 2>/dev/null; do
  sleep 1
done
"""


_STOP_TEMPLATE = """#!/usr/bin/env bash
# Graceful stop: send 'stop' to the MC console via tmux, wait, then let
# systemd finish. Prevents world corruption. Waits up to {stop_timeout_sec}s
# — controlled by stop_timeout_sec on the ServerDef; the handler clamps it
# under the systemd TimeoutStopSec=300 budget in systemd/gamesrv@.service.
set -euo pipefail
SESSION="gs-{name}"
if tmux has-session -t "$SESSION" 2>/dev/null; then
  tmux send-keys -t "$SESSION" "say Server stopping in 5s..." Enter || true
  sleep 5
  tmux send-keys -t "$SESSION" "stop" Enter || true
  # Heartbeat every 30s so the journal shows the stop is progressing.
  for i in $(seq 1 {stop_timeout_sec}); do
    tmux has-session -t "$SESSION" 2>/dev/null || exit 0
    if (( i % 30 == 0 )); then
      echo "stop.sh: still waiting for tmux session to exit (${{i}}s elapsed)" >&2
    fi
    sleep 1
  done
  echo "stop.sh: JVM did not exit within {stop_timeout_sec}s — systemd will now SIGKILL the cgroup" >&2
fi
"""


class MinecraftJavaHandler(TypeHandler):
    def install(self) -> list[str]:
        self.ensure_dirs()
        msgs: list[str] = []

        # A little headroom for JVM overhead — Xms half of Xmx is a decent default.
        xmx = max(512, self.sd.memory_mb)
        xms = max(512, xmx // 2)

        start_sh = _START_TEMPLATE.format(
            name=self.sd.name,
            xmx=xmx,
            xms=xms,
            extra_args=self.sd.java_args,
        )
        stop_timeout = resolve_stop_timeout(self.sd, default_sec=240)
        stop_sh = _STOP_TEMPLATE.format(name=self.sd.name, stop_timeout_sec=stop_timeout)

        self.write_script("start.sh", start_sh)
        self.write_script("stop.sh", stop_sh)
        msgs.append(f"wrote {self.install_dir/'start.sh'}")
        msgs.append(f"wrote {self.install_dir/'stop.sh'} (wait {stop_timeout}s)")

        # server.env: pass Minecraft options as env vars if needed later.
        env_values = {"MC_MEMORY_MB": str(self.sd.memory_mb), "MC_PORT": str(self.sd.port)}
        env_values.update(self.sd.extra_env)
        self.write_env_file(env_values)
        msgs.append(f"wrote {self.install_dir/'server.env'}")

        # Wake-on-demand: the manager's TCP proxy owns sd.port and MC has
        # to bind sd.port + 10000 instead. Force it via server.properties
        # (Minecraft honours this on next launch; --port on argv is less
        # reliable across launchers).
        if getattr(self.sd, "wake_on_demand", False):
            internal_port = self.sd.port + 10000
            msgs.append("wake-on-demand: " + self.patch_server_properties("server-port", str(internal_port)))
            msgs.append(f"wake-on-demand: game will bind :{internal_port}; proxy owns public :{self.sd.port}")

        # Symlink world into the install dir so Minecraft writes to the NFS bind mount.
        link = self.install_dir / "world"
        if not link.exists():
            link.symlink_to(self.world_dir)
            msgs.append(f"symlinked world -> {self.world_dir}")

        jar = self.install_dir / "server.jar"
        if not jar.exists():
            msgs.append("NOTE: upload server.jar (area=install, path=server.jar) before starting")

        return msgs

    def update(self) -> list[str]:
        # Minecraft updates = replace server.jar. Users upload the new jar and
        # then hit 'update' which just regenerates scripts (in case memory/args
        # changed) and confirms the jar is in place.
        msgs = self.install()
        jar = self.install_dir / "server.jar"
        if jar.exists():
            msgs.append(f"server.jar present ({jar.stat().st_size} bytes)")
        else:
            msgs.append("WARNING: server.jar still missing — upload it first")
        return msgs
