"""SteamCMD-based dedicated servers (Palworld, Satisfactory, Valheim, ARK, etc.).

We shell out to `steamcmd` to install/update. The user provides steam_app_id
in the server YAML (Palworld = 2394010, Satisfactory = 1690800). Anonymous
login covers most free-to-host dedicated servers.

Palworld notes (baked into the default start.sh):
  - Binary lives at Pal/Binaries/Linux/PalServer-Linux-Shipping
  - Also ships a top-level PalServer.sh wrapper — we call that.
  - Save data lives in Pal/Saved — we symlink Saved -> world_dir so the
    NFS bind mount holds saves.

Satisfactory notes:
  - Binary is FactoryServer.sh (top-level wrapper); single UDP port since
    Update 8 / 1.0 (game + query on the same port).
  - Saves live at $HOME/.config/Epic/FactoryGame/Saved on Linux, so the
    recipe pins HOME to install_dir and symlinks that Saved dir onto
    world_dir. Drop your existing .sav under world_dir/SaveGames/server/
    after Install.
"""
from __future__ import annotations

import os
import re
import select
import shutil
import subprocess
import time
from collections import deque

from .base import TypeHandler


_START_TEMPLATE = """#!/usr/bin/env bash
# Generated by gamesrv manager. Runs a SteamCMD-installed dedicated server
# inside tmux so the console channel + graceful stop work.
set -euo pipefail
cd "$(dirname "$0")"

SESSION="gs-{name}"
BIN="{run_cmd}"

if ! command -v tmux >/dev/null; then
  echo "ERROR: tmux is required (apt install tmux)" >&2
  exit 1
fi

# Truncate the tmux pane capture ONLY if the previous run left it huge
# (>10 MB — a full-day session of a chatty game like Palworld or ARK can
# reach that easily). Do NOT unconditionally truncate: if the process is
# crash-looping via systemd Restart=on-failure, every restart runs start.sh
# again, and blindly truncating here means the operator's only window into
# WHY it crashed (the last exit trace) gets wiped seconds later. Preserve
# it so the Console tab shows the accumulated log across restarts.
if [[ -f console.log ]] && [[ $(stat -c%s console.log 2>/dev/null || echo 0) -gt 10485760 ]]; then
  # Keep the last ~2 MB — enough for one or two crash traces.
  tail -c 2000000 console.log > console.log.tmp && mv console.log.tmp console.log
fi
# Marker so the operator can find where THIS launch begins in the log.
{{ echo ""; echo "===== $(date -Iseconds) start.sh launching (session $SESSION) ====="; }} >> console.log

tmux kill-session -t "$SESSION" 2>/dev/null || true

# Start tmux DETACHED, but wrap the actual game invocation so we can
# capture its true exit code. Without this wrapper, tmux swallows the
# game's exit code and start.sh always exits 0 — so systemd never sees
# a real failure signal and the operator's Console tab has no clue why
# the process died. With the wrapper:
#   * ${{BIN}} runs normally, writing stdout/stderr to the tmux pane
#     (which pipe-pane below tees to console.log).
#   * When it exits, the wrapper appends a GAMESRV_EXIT=<code> line to
#     console.log AND to stderr (visible in `journalctl -u gamesrv@<name>`).
#     Exit-code decoder: 0 clean exit, 130 SIGINT (external stop or
#     Palworld self-exit), 137 SIGKILL (OOM / cgroup memory limit), 139
#     SIGSEGV (native crash), 1/2/etc  Palworld's own error paths.
# The trailing `; exec bash` (commented out below) is available if you
# want the tmux window to persist after the game dies for hands-on
# debugging — enable by hand-editing start.sh; the manager won't
# regenerate over it if you also set MANAGED=false at the top.
tmux new-session -d -s "$SESSION" -n game \\
  "$BIN ; ec=\\$?; printf '\\nGAMESRV_EXIT=%d\\n' \\$ec | tee -a $(pwd)/console.log >&2"

# Tee the tmux pane's live output to console.log. This is the ONLY way the
# manager's Console tab can show game output for SteamCMD games that don't
# write their own log file to disk (Palworld, Valheim, generic steamcmd),
# because their stdout goes to the tmux pane — not the systemd journal.
# For games that DO write their own log (Satisfactory FactoryGame.log, ARK
# ShooterGame.log), the pane capture is a useful supplement showing early
# boot errors + steamcmd chatter before the game log opens.
# Non-fatal: if pipe-pane fails, the game still runs; the operator just
# won't see live output in the dashboard until the next Install regenerates
# start.sh. Older tmux (<2.6) may not accept ``-t sess:window`` — retry
# with just the session target if that happens.
tmux pipe-pane -t "$SESSION:game" "cat >> $(pwd)/console.log" 2>/dev/null \\
  || tmux pipe-pane -t "$SESSION" "cat >> $(pwd)/console.log" 2>/dev/null \\
  || echo "WARN: tmux pipe-pane failed; Console tab will fall back to systemd journal" >&2

while tmux has-session -t "$SESSION" 2>/dev/null; do
  sleep 1
done
"""


_STOP_TEMPLATE = """#!/usr/bin/env bash
# Most SteamCMD servers respond to SIGINT for a clean shutdown. tmux
# send-keys C-c then wait; systemd will hard-kill if we exceed the unit
# TimeoutStopSec.
set -euo pipefail
SESSION="gs-{name}"
if tmux has-session -t "$SESSION" 2>/dev/null; then
  tmux send-keys -t "$SESSION" C-c || true
  for _ in $(seq 1 60); do
    tmux has-session -t "$SESSION" 2>/dev/null || exit 0
    sleep 1
  done
fi
"""


# --- built-in run-command recipes per known app id ---------------------------
# Extend this dict when adding a new SteamCMD game.
#   name       — short label (informational)
#   run        — argv template; {name} and {port} are substituted
#   saves_rel  — path under install_dir that gets symlinked to world_dir
#                (None = no symlink; game writes saves inside install_dir)
#   env        — optional dict of extra env vars written to server.env;
#                {install_dir} and {world_dir} are substituted. Use this to
#                pin HOME for games that write saves under $HOME (Satisfactory).
#   wine       — True for Windows-only servers we run under Wine (Enshrouded).
#                Also implies steamcmd_platform="windows" so the Windows
#                depot is downloaded. `run` should be the .exe path — the
#                handler wraps it in `wine ...` and sets WINEPREFIX.
#   steamcmd_platform — "linux" (default) or "windows".
_APP_RECIPES: dict[int, dict] = {
    2394010: {  # Palworld dedicated
        "name": "palworld",
        # Launch args match the OFFICIAL Pocketpair Linux docs EXACTLY:
        # https://docs.palworldgame.com/getting-started/deploy-dedicated-server/
        # (Linux with SteamCMD tab)
        #
        # The docs show simply `./PalServer.sh` — no arguments at all.
        # Port defaults to 8211, controlled by PalWorldSettings.ini if
        # needed. Passing -useperfthreads / -NoAsyncLoadingThread /
        # -UseMultithreadForDS is explicitly discouraged on v1.0+ per
        # https://docs.palworldgame.com/settings-and-operation/arguments:
        #   "In v1.0 and later, leaving this parameter unset may improve
        #    performance."
        # Even -port= is skipped by the docs' example — the port comes
        # from PalWorldSettings.ini defaults (8211). To use a non-default
        # port, edit PublicPort in the ini via the Files tab. The
        # manager's _apply_palworld_passwords() already syncs PublicPort
        # from the server def's `port` field, so the def's port DOES
        # take effect via the ini path.
        "run": "./PalServer.sh",
        "saves_rel": "Pal/Saved",
        # HOME pinned to install_dir so Palworld's Steam Runtime state
        # (~/.steam/{sdk32,sdk64,registry.vdf}, ~/Steam/logs/) lands
        # somewhere gamesrv definitely owns and survives reinstalls
        # cleanly. The post-install hook _apply_palworld_steam_runtime
        # populates the required Steamworks SDK shim files under this
        # pinned HOME.
        #
        # The remaining env vars address a known headless-server hang:
        # Palworld's build calls SteamAPI_Init() (the client-side init)
        # AS WELL AS SteamGameServer_Init() (server-side). The former
        # tries to talk to a running Steam Client via
        # /dev/shm/u999-ValveIPCSharedObj-Steam and blocks its
        # IPC:CSteamEngin thread in do_epoll_wait forever when no client
        # is present. Main thread sits in hrtimer_nanosleep polling for
        # SteamAPI_Init to finish, world load never starts, card shows
        # "starting" indefinitely with RAM stuck ~1 GB. Confirmed via
        # /proc/PID/wchan diagnostics.
        #
        # * SteamAppId — tells the SDK the target app up front, skipping
        #   the "which app am I" discovery step that pokes Steam Client.
        # * SteamGameServer=1 — hints server-mode init path; some
        #   Steamworks builds honor this to skip Steam Client rendezvous.
        # * SDL_VIDEODRIVER / SDL_AUDIODRIVER=dummy — belt-and-suspenders
        #   for Unreal Engine, which can otherwise try to init graphics/
        #   audio libs headlessly and hang if they're not present.
        "env": {
            "HOME": "{install_dir}",
            "SteamAppId": "2394010",
            "SteamGameServer": "1",
            "SDL_VIDEODRIVER": "dummy",
            "SDL_AUDIODRIVER": "dummy",
            # Disable Sentry Native crash reporter. Palworld bundles
            # sentry-native (visible in /proc/PID/fd as Pal/.sentry-native/
            # *.run.lock). Sentry Native init runs early in Palworld's
            # boot and interacts with the Steamworks IPC event loop on
            # the same thread. When SteamAPI_Init() blocks waiting for a
            # Steam Client that isn't there, Sentry's crash-report path
            # can compound the deadlock — Palworld posts to Sentry when
            # a crash occurs, but the crash IS the SteamAPI deadlock, so
            # the Sentry HTTPS upload blocks further progress. Clearing
            # SENTRY_DSN tells sentry-native to skip network initialisation
            # entirely; it becomes a no-op. Palworld itself is unaffected.
            "SENTRY_DSN": "",
            "SENTRY_ENABLE_BACKEND": "0",
        },
    },
    1690800: {  # Satisfactory dedicated
        # Post-1.0 quirks (learned the hard way — see
        # docs/SATISFACTORY_NOTES.md and this class's install() hook):
        #   * Server needs THREE ports: game UDP on ``sd.port``, HTTPS API
        #     TCP on ``sd.port`` (forced by -ServerQueryPort; see below),
        #     and a fixed TCP 8888 for reliable messaging (save/asset
        #     streaming when clients join).  firewall.py's
        #     _extra_ports_for() opens all three.
        #   * ``-ServerQueryPort={port}`` is REQUIRED. Without it,
        #     FactoryServer's HTTPS Server API defaults to ``-Port + 1``
        #     (e.g. 15778 when -Port=15777) — the in-game Server Manager
        #     panel then shows "Offline" because it queries the same port
        #     as the game and gets nothing. Passing this flag pins the
        #     API to the same TCP port as the game's UDP port, so only
        #     one port ever needs to be forwarded on the router.
        #     Confirmed empirically 2026-07-10 after chasing an "API on
        #     15778" ghost for hours.
        #   * Direct-Connect ("Join Game") always fails with
        #     "Encryption token missing" — the client MUST use Server
        #     Manager to auth first and receive a session token.
        #   * SM caches per-(IP, PORT) key. If a bad connection ever
        #     wedges the client's state machine, changing the server port
        #     (e.g. 7777 → 15777) gives a fresh cache key and often
        #     unsticks it — we've seen this in the field.
        #   * The old AutoLoadSessionName ini directive is largely a
        #     no-op in 1.0+; server always boots into DedicatedserverEntry
        #     until Server Manager (or the HTTPS API's LoadGame call)
        #     tells it what to load.
        #   * Bootstrap via curl works (PasswordlessLogin → ClaimServer
        #     → LoadGame). See docs/SATISFACTORY_NOTES.md for the exact
        #     sequence.
        "name": "satisfactory",
        "run": "./FactoryServer.sh -Port={port} -ServerQueryPort={port} -log -unattended",
        # HOME is pinned so Epic/FactoryGame/Saved lands inside install_dir,
        # which we then symlink to world_dir below.
        "saves_rel": ".config/Epic/FactoryGame/Saved",
        "env": {"HOME": "{install_dir}"},
    },
    376030: {   # ARK: Survival Evolved dedicated (the ORIGINAL, not Ascended)
        # Ports: {port}/udp game + 27015/udp query + {port+1}/udp raw. Only
        # {port} and 27015 need to be open; the raw port is peer-to-peer.
        # Map is TheIsland by default — override by hand-editing start.sh
        # (or add a per-server recipe override later).
        "name": "ark-se",
        "run": "./ShooterGame/Binaries/Linux/ShooterGameServer TheIsland?SessionName={name}?listen?Port={port}?QueryPort=27015 -server -log",
        "saves_rel": "ShooterGame/Saved",
    },
    2430930: {  # ARK: Survival Ascended dedicated (Unreal 5, MUCH heavier)
        # Native Linux server support has been patchy across releases; if
        # steamcmd installs Windows-only files (no ShooterGame/Binaries/Linux)
        # you'll need to run it under Wine — that's a separate track we'll
        # add later. Map names use the _WP suffix (World Partition), e.g.
        # TheIsland_WP, ScorchedEarth_WP, Aberration_WP.
        "name": "ark-sa",
        "run": "./ShooterGame/Binaries/Linux/ArkAscendedServer TheIsland_WP?SessionName={name}?listen?Port={port}?QueryPort=27015 -server -log",
        "saves_rel": "ShooterGame/Saved",
    },
    896660: {   # Valheim dedicated
        "name": "valheim",
        "run": "./valheim_server.x86_64 -name '{name}' -port {port} -world 'Dedicated' -password 'CHANGE_ME_IN_START_SH' -public 0",
        "saves_rel": ".config/unity3d/IronGate/Valheim",
    },
    2278520: {  # Enshrouded Dedicated Server (Windows-only binary → Wine)
        # Enshrouded ships a Windows-only .exe. We install the Windows depot
        # via steamcmd (+@sSteamCmdForcePlatformType windows) and run it
        # under Wine. Reads enshrouded_server.json in the install dir for
        # port + password config (the handler writes/patches it on Install
        # from ServerDef.passwords + port). Saves land in savegame/ which
        # we symlink to world_dir. Default game/query ports: 15636 / 15637.
        "name": "enshrouded",
        "run": "./enshrouded_server.exe",
        "saves_rel": "savegame",
        "wine": True,
        "steamcmd_platform": "windows",
    },
}


# --- progress parsing --------------------------------------------------------
# SteamCMD emits two shapes we care about:
#
#   "Update state (0x61) downloading, progress: 45.30 (4746854400 / 10485760000)"
#     -> phase="downloading", percent=45.30, bytes_done/total
#
#   "[ 45%] Downloading update (4634 of 10240 KB)..."
#     -> percent + phase text (used during the early "checking / verifying"
#        stages before the numeric Update state lines appear)
#
# Success line: "Success! App '2394010' fully installed."
_PROGRESS_RE = re.compile(
    r"Update state \(0x[0-9a-fA-F]+\)\s+([^,]+?),\s+progress:\s+([\d.]+)\s+\((\d+)\s*/\s*(\d+)\)"
)
_BRACKET_RE = re.compile(r"^\[\s*(\d+)%\]\s*(.+?)\s*$")
_SUCCESS_RE = re.compile(r"Success!\s+App\s+'(\d+)'\s+fully installed", re.IGNORECASE)

# Timeout for the whole steamcmd invocation. Palworld ~4 GB, Satisfactory
# ~7 GB, ARK 20+ GB — on a slow connection an hour can be tight, so 2h.
_STEAMCMD_TIMEOUT_SEC = 60 * 60 * 2


def _parse_line(line: str) -> dict | None:
    """Turn a steamcmd stdout line into a progress event, or None."""
    m = _PROGRESS_RE.search(line)
    if m:
        try:
            return {
                "phase": m.group(1).strip(),
                "percent": float(m.group(2)),
                "bytes_done": int(m.group(3)),
                "bytes_total": int(m.group(4)),
            }
        except ValueError:
            return None
    if _SUCCESS_RE.search(line):
        return {"phase": "complete", "percent": 100.0}
    m = _BRACKET_RE.match(line)
    if m:
        try:
            return {
                "phase": m.group(2).strip(" ."),
                "percent": float(m.group(1)),
            }
        except ValueError:
            return None
    return None


def _stream_steamcmd(cmd: list[str], on_event, env: dict | None = None) -> tuple[int, str]:
    """Run steamcmd; stream stdout line-by-line into on_event({...}).

    Handles both \\n-terminated lines and steamcmd's \\r-updated download
    progress (which would otherwise be one giant line). Returns
    (returncode, tail_str) where tail_str is the last ~40 lines for logs.

    ``env`` is passed through to ``subprocess.Popen`` unchanged. Pass the
    manager process env plus per-recipe overrides (notably ``HOME``, which
    steamcmd needs writable to store its own state). ``None`` means inherit
    — safe for tests, wrong for production because the manager's HOME may
    be unwritable by the effective user.
    """
    proc = subprocess.Popen(
        cmd,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        bufsize=0,
        env=env,
    )
    assert proc.stdout is not None
    fd = proc.stdout.fileno()
    # Non-blocking so we can service \r-only "carriage return" progress
    # updates without waiting for a full line.
    try:
        os.set_blocking(fd, False)
    except (OSError, AttributeError):
        pass

    tail: deque[str] = deque(maxlen=40)
    buf = b""
    started = time.monotonic()

    def _emit_line(raw: str) -> None:
        line = raw.rstrip()
        if not line:
            return
        tail.append(line)
        event = {"line": line}
        parsed = _parse_line(line)
        if parsed:
            event.update(parsed)
        on_event(event)

    try:
        while True:
            try:
                ready, _, _ = select.select([fd], [], [], 0.5)
            except (OSError, ValueError):
                ready = []
            if ready:
                try:
                    chunk = os.read(fd, 4096)
                except (BlockingIOError, OSError):
                    chunk = b""
                if not chunk:
                    if proc.poll() is not None:
                        break
                else:
                    buf += chunk
                    parts = re.split(rb"[\r\n]+", buf)
                    buf = parts[-1]
                    for raw in parts[:-1]:
                        _emit_line(raw.decode("utf-8", "replace"))
            elif proc.poll() is not None:
                break

            if time.monotonic() - started > _STEAMCMD_TIMEOUT_SEC:
                proc.kill()
                raise RuntimeError(
                    f"steamcmd timed out after {_STEAMCMD_TIMEOUT_SEC // 60} minutes"
                )

        if buf:
            _emit_line(buf.decode("utf-8", "replace"))
    finally:
        try:
            proc.stdout.close()
        except Exception:
            pass

    try:
        proc.wait(timeout=10)
    except subprocess.TimeoutExpired:
        proc.kill()
        proc.wait(timeout=5)

    return proc.returncode, "\n".join(tail)


# ---------- per-game password injection --------------------------------------

# Characters that break the game's own parsing when embedded inline. We
# don't try to escape — we refuse (with a clear message) so the operator
# picks a saner password.
_PW_FORBIDDEN_ARK = set('?&"\' ')
_PW_FORBIDDEN_VALHEIM = set('"\' ')


def _apply_ark_passwords(run_cmd: str, server_pw: str, admin_pw: str) -> tuple[str, str]:
    """Append ?ServerPassword=... / ?ServerAdminPassword=... to ARK's URL.

    ARK's launch string is ``<Map>?<key1=val1>?<key2=val2> -server -log``.
    We insert our password params just before the first `` -``-prefixed
    switch (safe because our recipe never uses `` -`` inside the URL).
    """
    parts: list[str] = []
    for label, val, key in (
        ("server_password", server_pw, "ServerPassword"),
        ("admin_password", admin_pw, "ServerAdminPassword"),
    ):
        if not val:
            continue
        if any(c in _PW_FORBIDDEN_ARK for c in val):
            return run_cmd, (
                f"WARNING: ARK {label} contains forbidden chars "
                f"(any of `{''.join(sorted(_PW_FORBIDDEN_ARK))}`); skipped injection."
            )
        parts.append(f"?{key}={val}")
    if not parts:
        return run_cmd, ""
    insertion = "".join(parts)
    # Split at first " -" (start of a launch switch).
    idx = run_cmd.find(" -")
    if idx < 0:
        new_cmd = run_cmd + insertion
    else:
        new_cmd = run_cmd[:idx] + insertion + run_cmd[idx:]
    return new_cmd, f"ARK: injected {len(parts)} password param(s) into launch URL"


def _apply_valheim_passwords(run_cmd: str, server_pw: str) -> tuple[str, str]:
    """Replace the recipe's placeholder password with the real one.

    Valheim has no separate admin password (admins are steamID64 lines in
    adminlist.txt); we only touch the server-join password here.
    """
    if not server_pw:
        return run_cmd, ""
    if any(c in _PW_FORBIDDEN_VALHEIM for c in server_pw):
        return run_cmd, (
            "WARNING: Valheim password contains spaces or quotes; skipped injection. "
            "Pick a password without those characters."
        )
    # Recipe's placeholder is literal 'CHANGE_ME_IN_START_SH'.
    if "CHANGE_ME_IN_START_SH" not in run_cmd:
        return run_cmd, "NOTE: Valheim recipe placeholder not found; leaving run_cmd alone."
    return (
        run_cmd.replace("CHANGE_ME_IN_START_SH", server_pw),
        "Valheim: injected server password into -password arg",
    )


# Palworld config editing — the game reads a single monolithic
# OptionSettings=(K=V,K=V,...) line inside
# Pal/Saved/Config/LinuxServer/PalWorldSettings.ini.
_PALWORLD_KV_RE = re.compile(r'([A-Za-z]+)=("(?:[^"\\]|\\.)*")')


# Offset applied by wake-on-demand: the game process binds public_port +
# this, and the wake proxy owns the public port. Kept in sync with
# app/wake_proxy.py WAKE_INTERNAL_OFFSET.
_WAKE_INTERNAL_OFFSET = 10000


def _effective_game_port(sd) -> int:
    """Port the game process actually binds.

    - Without wake-on-demand: the operator-facing `sd.port` (unchanged).
    - With wake-on-demand: sd.port + 10000, so the wake proxy can own the
      public port and relay traffic.
    """
    if getattr(sd, "wake_on_demand", False):
        return sd.port + _WAKE_INTERNAL_OFFSET
    return sd.port


def _apply_palworld_passwords(install_dir, port: int, server_pw: str, admin_pw: str) -> str:
    """Copy DefaultPalWorldSettings.ini if needed and set port + passwords.

    Since the Palworld recipe no longer passes ``-port=`` on the command
    line (it was one variable we couldn't rule out in the SteamAPI-init
    hang debugging), the port MUST be set here in ``PalWorldSettings.ini``
    via the ``PublicPort`` field. Palworld reads this to decide what UDP
    port to bind.
    """
    default_ini = install_dir / "DefaultPalWorldSettings.ini"
    target_ini = install_dir / "Pal" / "Saved" / "Config" / "LinuxServer" / "PalWorldSettings.ini"

    if target_ini.exists():
        text = target_ini.read_text(encoding="utf-8")
    elif default_ini.exists():
        target_ini.parent.mkdir(parents=True, exist_ok=True)
        text = default_ini.read_text(encoding="utf-8")
    else:
        return (
            "WARNING: Palworld DefaultPalWorldSettings.ini not found; "
            "port + passwords NOT applied. Complete the install first, then set "
            "them manually in Pal/Saved/Config/LinuxServer/PalWorldSettings.ini."
        )

    changed: list[str] = []

    def _set_quoted(text: str, key: str, val: str) -> str:
        """Replace ``Key="..."`` — Palworld's quoted string fields."""
        safe = val.replace('"', "'")   # Palworld disallows inline double quotes
        pattern = re.compile(rf'({re.escape(key)}=)"([^"]*)"')
        if not pattern.search(text):
            return text
        return pattern.sub(lambda m: f'{m.group(1)}"{safe}"', text)

    def _set_number(text: str, key: str, val: int) -> str:
        """Replace ``Key=NNNN`` — Palworld's numeric fields (port, etc)."""
        pattern = re.compile(rf'({re.escape(key)}=)(\d+)')
        if not pattern.search(text):
            return text
        return pattern.sub(lambda m: f'{m.group(1)}{val}', text)

    # Port — always applied so the server binds where the def says.
    new_text = _set_number(text, "PublicPort", int(port))
    if new_text != text:
        changed.append(f"PublicPort={port}")
        text = new_text

    if server_pw:
        new_text = _set_quoted(text, "ServerPassword", server_pw)
        if new_text != text:
            changed.append("ServerPassword")
            text = new_text
    if admin_pw:
        new_text = _set_quoted(text, "AdminPassword", admin_pw)
        if new_text != text:
            changed.append("AdminPassword")
            text = new_text

    if not changed:
        return "NOTE: Palworld config file keys not found; nothing changed."

    target_ini.write_text(text, encoding="utf-8")
    return f"Palworld: wrote {target_ini.name} with updated {', '.join(changed)}"


# ---------- Enshrouded (JSON config) -----------------------------------------

def _apply_enshrouded_config(install_dir, name: str, port: int,
                             server_pw: str, admin_pw: str) -> str:
    """Create or patch enshrouded_server.json in install_dir.

    Enshrouded's dedicated server ships with a JSON config next to the .exe.
    Field of interest:
      - gamePort  (default 15636)
      - queryPort (default 15637, must be gamePort + 1)
      - name      (server list display name)
      - userGroups[].password  — one entry per group; we set 'Admin' and 'Guest'.

    If the file already exists we surgically update those fields (preserving
    every other field the operator may have hand-tuned). If it doesn't, we
    write a minimal template.
    """
    import json as _json

    cfg_path = install_dir / "enshrouded_server.json"
    game_port = port
    query_port = port + 1

    if cfg_path.exists():
        try:
            cfg = _json.loads(cfg_path.read_text(encoding="utf-8"))
        except Exception as e:
            return f"WARNING: existing enshrouded_server.json unparseable ({e}); left alone."
    else:
        cfg = {
            "name": name,
            "password": "",
            "saveDirectory": "./savegame",
            "logDirectory": "./logs",
            "ip": "0.0.0.0",
            "gamePort": game_port,
            "queryPort": query_port,
            "slotCount": 16,
            "voiceChatMode": "Proximity",
            "userGroups": [
                {"name": "Admin", "password": "", "canKickBan": True,
                 "canAccessInventories": True, "canEditBase": True,
                 "canExtendBase": True, "reservedSlots": 0},
                {"name": "Guest", "password": "", "canKickBan": False,
                 "canAccessInventories": True, "canEditBase": True,
                 "canExtendBase": False, "reservedSlots": 0},
            ],
        }

    changed: list[str] = []

    if cfg.get("gamePort") != game_port:
        cfg["gamePort"] = game_port
        changed.append("gamePort")
    if cfg.get("queryPort") != query_port:
        cfg["queryPort"] = query_port
        changed.append("queryPort")

    groups = cfg.get("userGroups") or []
    def _set_group_pw(group_name: str, pw: str, label: str) -> None:
        for g in groups:
            if str(g.get("name", "")).lower() == group_name.lower():
                if g.get("password") != pw:
                    g["password"] = pw
                    changed.append(f"userGroups[{group_name}].password")
                return
        # Group not found — append it (rare, but keep behaviour sane).
        groups.append({"name": group_name, "password": pw})
        changed.append(f"userGroups[+{group_name}]")

    if admin_pw:
        _set_group_pw("Admin", admin_pw, "Admin")
    if server_pw:
        _set_group_pw("Guest", server_pw, "Guest")
    cfg["userGroups"] = groups

    cfg_path.write_text(_json.dumps(cfg, indent=2), encoding="utf-8")
    if not changed:
        return "Enshrouded: enshrouded_server.json already matched YAML; no changes."
    return f"Enshrouded: wrote enshrouded_server.json ({', '.join(changed)})"


# ---------- Wine wrapper -----------------------------------------------------

# Wrap the recipe's `run` (a path to a .exe) in Wine, with WINEPREFIX/DEBUG
# baked into start.sh so the systemd unit doesn't need any extra env plumbing.
def _wine_wrap_run_cmd(run_cmd: str) -> str:
    return (
        'WINEPREFIX="$(pwd)/.wine" WINEDEBUG=-all WINEARCH=win64 '
        'wine ' + run_cmd
    )


def _wine_prefix_init(install_dir, on_event=None) -> str:
    """Idempotently initialise the wineprefix under install_dir/.wine.

    First `wineboot -u` on a fresh prefix takes ~10-30s; subsequent runs
    are ~1s. Errors are non-fatal — a bad init just means the first game
    launch will re-attempt.
    """
    wine = shutil.which("wine")
    if not wine:
        raise RuntimeError(
            "wine not installed — re-run bootstrap.sh with --with-wine (see docs/ADDING_SERVERS.md §10)."
        )
    prefix = install_dir / ".wine"
    prefix.mkdir(parents=True, exist_ok=True)
    env = os.environ.copy()
    env.update({
        "WINEPREFIX": str(prefix),
        "WINEDEBUG": "-all",
        "WINEARCH": "win64",
        "DISPLAY": "",  # explicitly headless — no X server
    })
    if on_event:
        on_event({"phase": "wineboot", "line": f"initialising wineprefix at {prefix}"})
    try:
        r = subprocess.run(
            [wine, "wineboot", "-u"],
            env=env, capture_output=True, text=True, timeout=120,
        )
    except subprocess.TimeoutExpired:
        return f"WARNING: wineboot timed out after 120s (prefix {prefix}); first game launch may re-init."
    if r.returncode != 0:
        return (
            f"WARNING: wineboot exit {r.returncode} — first game launch may re-init.\n"
            f"stderr tail: {(r.stderr or '')[-400:]}"
        )
    return f"Wine: initialised prefix {prefix}"


# ---------- install-time pre-flight -----------------------------------------

# Rough minimum free-disk requirements per known SteamCMD app id (in GB).
# Sized to cover: the initial download, the extracted install, a full
# validate re-download of every file (steamcmd does this on every "install"),
# plus a bit of headroom for the game's first-boot world/config creation.
# Numbers err on the high side — a false-positive "not enough disk" is
# cheap to fix (delete something, retry); a false-negative (partial install
# because df ran out mid-download) leaves install_dir wedged.
_MIN_DISK_GB: dict[int, int] = {
    2394010: 8,    # Palworld (~4 GB game)
    1690800: 15,   # Satisfactory (~7 GB game + updates)
    376030:  35,   # ARK: Survival Evolved (~20 GB game)
    2430930: 60,   # ARK: Survival Ascended (heavy Unreal 5 build)
    896660:  4,    # Valheim (~1.5 GB game)
    2278520: 30,   # Enshrouded (Wine prefix + ~10 GB game + shader cache)
}
_DEFAULT_MIN_DISK_GB = 10   # generic SteamCMD game with no per-app entry


def _preflight_writable(path, label: str) -> None:
    """Fail fast if ``path`` isn't writable by the running user.

    This catches the two most common LXC/bind-mount misconfigurations:
      * ``install_dir`` owned by root because it was pre-created with
        ``mkdir`` as root before ``chown``ing to gamesrv.
      * ``world_dir`` on a squashed NFS/bind mount showing up as
        ``nobody:nogroup`` (or otherwise not writable by gamesrv).

    Both fail silently later on: SteamCMD partially extracts, then the
    game process crashes on first save without a clear log line. Refusing
    at Install time with an actionable ``chown``/mount hint saves the
    operator hours.
    """
    try:
        path.mkdir(parents=True, exist_ok=True)
    except OSError as e:
        raise RuntimeError(
            f"{label} {path} is not creatable ({e}). "
            f"Check that its parent directory is writable by the manager user "
            f"(usually: sudo chown -R gamesrv:gamesrv {path.parent})."
        )
    probe = path / ".gamesrv_write_test"
    try:
        probe.write_text("ok", encoding="utf-8")
    except OSError as e:
        # Try to include ownership in the error so the operator has a hint
        # without needing to shell in.
        try:
            st = path.stat()
            import pwd, grp
            try:
                owner = pwd.getpwuid(st.st_uid).pw_name
            except KeyError:
                owner = str(st.st_uid)
            try:
                group = grp.getgrgid(st.st_gid).gr_name
            except KeyError:
                group = str(st.st_gid)
            owner_info = f" [current owner: {owner}:{group}, mode {oct(st.st_mode & 0o777)}]"
        except OSError:
            owner_info = ""
        raise RuntimeError(
            f"{label} {path} is not writable by the manager user ({e}).{owner_info} "
            f"Fix:\n"
            f"  sudo chown -R gamesrv:gamesrv {path}\n"
            f"If {label} is on a bind/NFS mount that squashes UIDs (owner shows as "
            f"'nobody:nogroup'), fix the mount options — see docs/ADDING_SERVERS.md "
            f"for the Proxmox bind-mount / TrueNAS NFS export recipe."
        )
    finally:
        try:
            probe.unlink()
        except OSError:
            pass


def _preflight_disk_space(install_dir, steam_app_id: int) -> None:
    """Fail fast if the filesystem hosting install_dir doesn't have room.

    SteamCMD downloads the full app to a temp area under HOME (which we
    pin to install_dir) and THEN moves files into place, so we can check
    a single mount point. Uses a per-app minimum (see _MIN_DISK_GB).
    """
    try:
        free_bytes = shutil.disk_usage(install_dir).free
    except OSError:
        return  # can't check; don't block the install on our own error
    min_gb = _MIN_DISK_GB.get(steam_app_id, _DEFAULT_MIN_DISK_GB)
    free_gb = free_bytes / (1024 ** 3)
    if free_gb < min_gb:
        raise RuntimeError(
            f"insufficient disk space on the filesystem hosting {install_dir}: "
            f"{free_gb:.1f} GB free, need at least {min_gb} GB for app "
            f"{steam_app_id}. Free some space and retry."
        )


class SteamCmdHandler(TypeHandler):
    def install(self) -> list[str]:
        if not self.sd.steam_app_id:
            raise ValueError("steamcmd type requires steam_app_id in the definition")
        self.ensure_dirs()
        msgs: list[str] = []

        # ---- pre-flight checks -----------------------------------------
        # Run these BEFORE steamcmd so the operator gets an actionable error
        # in seconds rather than after a multi-GB download partially completes
        # and leaves install_dir in a wedged half-installed state.
        _preflight_writable(self.install_dir, "install_dir")
        _preflight_writable(self.world_dir, "world_dir")
        _preflight_disk_space(self.install_dir, self.sd.steam_app_id)
        # ---------------------------------------------------------------

        # Locate steamcmd. Debian's package installs the binary at
        # /usr/games/steamcmd, which isn't on the default systemd PATH,
        # so shutil.which("steamcmd") returns None until the operator
        # symlinks it or edits PATH. Fall back to the known Debian path
        # so an unmodified apt-install "just works".
        steamcmd = shutil.which("steamcmd")
        if not steamcmd:
            for candidate in ("/usr/games/steamcmd", "/usr/local/bin/steamcmd", "/usr/bin/steamcmd"):
                if os.path.isfile(candidate) and os.access(candidate, os.X_OK):
                    steamcmd = candidate
                    break
        if not steamcmd:
            raise RuntimeError(
                "steamcmd not installed — run: sudo apt install steamcmd "
                "(and if `which steamcmd` still shows nothing after install, "
                "symlink it: sudo ln -sf /usr/games/steamcmd /usr/local/bin/steamcmd)"
            )

        # Look up the recipe up front so we know whether this is a Wine game
        # (which controls the steamcmd platform switch below).
        recipe = _APP_RECIPES.get(self.sd.steam_app_id, {
            "name": "generic",
            "run": self.sd.start_cmd or "./start.sh",
            "saves_rel": None,
        })
        steamcmd_platform = recipe.get("steamcmd_platform", "linux")
        uses_wine = bool(recipe.get("wine"))

        # Anonymous install/update. +force_install_dir must come BEFORE +login.
        cmd = [
            steamcmd,
            "+@sSteamCmdForcePlatformType", steamcmd_platform,
            "+force_install_dir", str(self.install_dir),
            "+login", "anonymous",
            "+app_update", str(self.sd.steam_app_id),
        ]
        if self.sd.steam_beta:
            cmd += ["-beta", self.sd.steam_beta]
        cmd += ["validate", "+quit"]

        msgs.append(f"running: {' '.join(cmd)}")
        self._emit(phase="starting steamcmd", percent=0.0, line=" ".join(cmd))

        # Build the steamcmd subprocess env. Pinning HOME to install_dir
        # is the safe default for every recipe: steamcmd writes ~/.steam,
        # ~/.local/share/Steam, ~/Steam etc., and the manager's own HOME
        # (systemd's User= default) is /home/gamesrv — which doesn't have
        # to exist. When it doesn't, steamcmd fails with "mkdir: cannot
        # create directory '/home': Permission denied" (issue seen on
        # unprivileged LXCs where /home is a tmpfs the service can't
        # extend). Sandboxing per-game state under install_dir also means
        # a game and its steamcmd cache are one unit — easy to back up
        # or move.
        run_env = os.environ.copy()
        run_env["HOME"] = str(self.install_dir)
        for k, v in (recipe.get("env") or {}).items():
            run_env[k] = v.format(install_dir=self.install_dir, world_dir=self.world_dir)

        rc, tail = _stream_steamcmd(cmd, lambda ev: self._emit(**ev), env=run_env)
        msgs.append(tail)
        if rc != 0:
            raise RuntimeError(f"steamcmd failed (exit {rc}):\n{tail}")

        self._emit(phase="finalising", percent=100.0, line="writing start.sh + stop.sh")

        # Everything past this point regenerates launch scripts, env files,
        # save-dir symlinks and per-game config from the current ServerDef.
        # It's factored out so `configure()` can re-run it on every Start
        # without re-downloading via steamcmd — that's what makes toggling
        # e.g. `wake_on_demand` take effect immediately.
        msgs.extend(self.configure())
        return msgs

    def configure(self) -> list[str]:
        """Regenerate scripts + env + symlinks from the current def.

        Idempotent; safe to call on every Start. Does NOT run steamcmd,
        so it's fast (subsecond). Called both at the tail of install()
        and by the manager's start/restart action so config changes like
        toggling wake_on_demand always take effect on the next launch."""
        if not self.sd.steam_app_id:
            raise ValueError("steamcmd type requires steam_app_id in the definition")
        self.ensure_dirs()
        msgs: list[str] = []

        recipe = _APP_RECIPES.get(self.sd.steam_app_id, {
            "name": "generic",
            "run": self.sd.start_cmd or "./start.sh",
            "saves_rel": None,
        })
        uses_wine = bool(recipe.get("wine"))

        game_port = _effective_game_port(self.sd)
        run_cmd = recipe["run"].format(name=self.sd.name, port=game_port)
        # Palworld special case: docs show `./PalServer.sh` with no args;
        # port defaults to 8211. If the operator picked a different port,
        # we still need to override via `-port=N` (docs list this arg as
        # valid). Appending it only when non-default keeps the launch
        # line matching Pocketpair's example verbatim in the common case.
        if self.sd.steam_app_id == 2394010 and game_port != 8211:
            run_cmd = f"{run_cmd} -port={game_port}"
        if self.sd.wake_on_demand:
            msgs.append(
                f"wake-on-demand: game will bind :{game_port} internally; "
                f"wake-proxy owns public :{self.sd.port}"
            )

        # Wine wrap (Windows binaries run through Wine). Do this AFTER the
        # per-game password / access blocks below so any switches they added
        # to run_cmd stay inside the wine invocation.

        # --- access control -------------------------------------------------
        # Per-game translation of ServerDef.access.mode. We handle steamid
        # allowlists inline here (writing config files + amending the run
        # command); the ip_allowlist mode is enforced at the firewall by
        # the separate gamesrv-firewall helper.
        access = self.sd.access
        if access.mode == "steamid_allowlist":
            n = len(access.allowed_steamids)
            if self.sd.steam_app_id in (376030, 2430930):
                # ARK: SE / Ascended. PlayerExclusiveJoinList.txt lists the
                # steamID64s that are allowed to join when -exclusivejoin is
                # on the command line. Empty file + -exclusivejoin locks
                # everyone out, which is safe-fail behaviour.
                saved = self.install_dir / "ShooterGame" / "Saved"
                saved.mkdir(parents=True, exist_ok=True)
                (saved / "PlayerExclusiveJoinList.txt").write_text(
                    "\n".join(access.allowed_steamids) + ("\n" if n else ""),
                    encoding="utf-8",
                )
                if " -exclusivejoin" not in run_cmd:
                    run_cmd += " -exclusivejoin"
                msgs.append(f"ARK: wrote PlayerExclusiveJoinList.txt ({n} entries) + enabled -exclusivejoin")
            else:
                # Games without a native Steam ID whitelist. Warn loudly so
                # the operator knows the setting isn't enforced by the game
                # (they need password + ip_allowlist to lock it down).
                msgs.append(
                    f"WARNING: access.mode=steamid_allowlist but app_id "
                    f"{self.sd.steam_app_id} has no native Steam ID whitelist. "
                    "Set a password in the game's config and/or use ip_allowlist."
                )
        elif access.mode == "ip_allowlist":
            msgs.append(
                f"NOTE: access.mode=ip_allowlist with {len(access.allowed_ips)} entries. "
                "Enforcement is at the firewall (see docs/ADDING_SERVERS.md#access-control)."
            )

        # --- passwords -------------------------------------------------------
        # Per-game injection. Each helper mutates run_cmd (returning the new
        # value) and appends a message describing what it did.
        pw = self.sd.passwords
        # Palworld always needs a config-file write to set PublicPort, since
        # the recipe no longer passes -port= on the command line. Run the
        # helper unconditionally for Palworld — passwords are optional.
        if self.sd.steam_app_id == 2394010:
            m = _apply_palworld_passwords(
                self.install_dir, game_port,
                pw.server_password, pw.admin_password,
            )
            if m: msgs.append(m)
        if pw.server_password or pw.admin_password:
            if self.sd.steam_app_id in (376030, 2430930):
                run_cmd, m = _apply_ark_passwords(run_cmd, pw.server_password, pw.admin_password)
                if m: msgs.append(m)
            elif self.sd.steam_app_id == 896660:
                run_cmd, m = _apply_valheim_passwords(run_cmd, pw.server_password)
                if m: msgs.append(m)
            elif self.sd.steam_app_id == 2278520:
                # Enshrouded — passwords go into userGroups in the JSON config.
                # Note: passing game_port so the JSON reflects the wake-remapped
                # port when wake-on-demand is on.
                m = _apply_enshrouded_config(
                    self.install_dir, self.sd.name, game_port,
                    pw.server_password, pw.admin_password,
                )
                if m: msgs.append(m)
            else:
                msgs.append(
                    f"NOTE: passwords set but no per-game injection for app_id "
                    f"{self.sd.steam_app_id}; edit the game's config by hand."
                )

        # Enshrouded always needs a config file (for its port), even when
        # passwords aren't set. Ensure one exists.
        if self.sd.steam_app_id == 2278520 and not (pw.server_password or pw.admin_password):
            m = _apply_enshrouded_config(
                self.install_dir, self.sd.name, game_port, "", "",
            )
            if m: msgs.append(m)

        # Wine games: initialise the wineprefix (idempotent) and wrap the
        # run command. Do this AFTER access + password mutations so the wine
        # invocation covers the final launch argv.
        if uses_wine:
            self._emit(phase="wine setup", line="initialising wineprefix")
            m = _wine_prefix_init(self.install_dir, on_event=lambda ev: self._emit(**ev))
            if m: msgs.append(m)
            run_cmd = _wine_wrap_run_cmd(run_cmd)
            msgs.append(f"Wine: wrapped run command → {run_cmd}")

        self.write_script(
            "start.sh",
            _START_TEMPLATE.format(name=self.sd.name, run_cmd=run_cmd),
        )
        self.write_script("stop.sh", _STOP_TEMPLATE.format(name=self.sd.name))
        msgs.append(f"wrote {self.install_dir/'start.sh'}")

        # Symlink the game's saves dir onto the NFS-backed world_dir.
        if recipe["saves_rel"]:
            saves = self.install_dir / recipe["saves_rel"]
            saves.parent.mkdir(parents=True, exist_ok=True)
            if saves.is_symlink() or saves.exists():
                if saves.is_symlink():
                    saves.unlink()
                elif saves.is_dir() and not any(saves.iterdir()):
                    saves.rmdir()
                else:
                    msgs.append(
                        f"WARNING: {saves} exists and is not a symlink; leaving alone. "
                        "Move its contents to world_dir and delete it, then re-run install."
                    )
            if not saves.exists():
                saves.symlink_to(self.world_dir)
                msgs.append(f"symlinked {saves} -> {self.world_dir}")

            # Verify the symlink actually resolves AND the target is
            # writable by us. Catches: TrueNAS/NFS mount dropped, world_dir
            # squashed to nobody:nogroup on a misconfigured bind mount,
            # world_dir on a read-only ZFS snapshot. Same pattern as the
            # top-of-install()  _preflight_writable — refuse loudly rather
            # than let the game crash on its first save.
            try:
                _preflight_writable(saves, f"save symlink {saves.name} -> world_dir")
            except RuntimeError as e:
                # Surface as a HARD failure — first save would crash the
                # game anyway, and we want the operator to see this in the
                # install job output, not in tmux console 5 minutes later.
                raise RuntimeError(
                    f"Save directory not usable after symlink to world_dir.\n{e}"
                ) from None

        env_values = {"GAME_PORT": str(game_port), "MEMORY_MB": str(self.sd.memory_mb)}
        # Recipe-provided env (e.g. HOME for Satisfactory) is applied before
        # user extras so the user's YAML always wins.
        for k, v in (recipe.get("env") or {}).items():
            env_values[k] = v.format(install_dir=self.install_dir, world_dir=self.world_dir)
        env_values.update(self.sd.extra_env)
        self.write_env_file(env_values)
        msgs.append(f"wrote {self.install_dir/'server.env'}")

        # Per-game post-install hook. Right now only Satisfactory needs it:
        # if the operator uploaded a .sav into world_dir/SaveGames/server/,
        # write the AutoLoadSessionName directive so the game actually
        # picks it up on first boot without a Server-Manager claim dance.
        # This saves the operator from having to hand-craft Game.ini.
        try:
            msgs.extend(_apply_post_install_config(self.sd, self.install_dir, self.world_dir))
        except Exception as e:
            msgs.append(f"WARNING: post-install config hook failed: {e}")

        return msgs

    def update(self) -> list[str]:
        # For SteamCMD games, update == re-run install (validates + patches).
        return self.install()


# --- per-game post-install config hooks --------------------------------------

def _apply_post_install_config(sd, install_dir, world_dir) -> list[str]:
    """Idempotent per-game config writer. Runs after every install/configure.

    Dispatches by ``sd.steam_app_id`` to per-game helpers:
      * Palworld (2394010) — populate ``$HOME/.steam/sdk{32,64}/`` with
        real Steam runtime libraries so ``SteamAPI_Init()`` completes
        instead of spinning forever waiting for a Steam Client that
        doesn't exist.
      * Satisfactory (1690800) — writes ``AutoLoadSessionName`` pointing
        at the newest ``.sav`` under ``world_dir``.

    Kept as a single dispatch function so future games can slot in without
    touching the main install() path.
    """
    if sd.steam_app_id == 2394010:
        return _apply_palworld_steam_runtime(install_dir)
    if sd.steam_app_id == 1690800:
        return _apply_satisfactory_autoload(sd, install_dir, world_dir)
    return []


def _apply_palworld_steam_runtime(install_dir) -> list[str]:
    """Set up the Steam Runtime shim files Palworld's SteamAPI needs.

    THE HANG THIS FIXES (evidenced by /proc/PID/wchan diagnostics):

      Palworld's ``SteamAPI_Init()`` succeeds partially (loads its LOCAL
      ``Pal/Binaries/Linux/steamclient.so``), then starts the
      ``IPC:CSteamEngin`` thread which uses ``/dev/shm/u999-ValveIPCSharedObj-Steam``
      to talk to a running Steam Client. On a dedicated server host with
      no Steam Client installed, that IPC thread blocks in ``epoll_wait``
      forever waiting for messages that never come.

      Meanwhile Palworld's main thread sits in ``hrtimer_nanosleep``
      polling SteamAPI status every few ms. Neither side ever completes,
      neither side crashes, no error is printed. The card shows
      "◐ starting" forever, RAM sits at 800 MB - 1 GB (engine loaded,
      world load never starts), and there's no signal in any log about
      what's wrong.

    THE FIX:

      Populate ``$HOME/.steam/sdk64/steamclient.so`` (and sdk32 for
      completeness) with a REAL Steam Runtime library — the one that
      SteamCMD installs when it initialises its own state. This is what
      LinuxGSM, official Palworld VPS guides, and every working
      Palworld-on-Linux setup does. The library's "server mode" fallback
      code path detects that no Steam Client is running and completes
      init WITHOUT trying to talk to one.

      CRITICAL: the symlink target MUST be a SteamCMD-provided
      ``steamclient.so``, NOT the game's own
      ``Pal/Binaries/Linux/steamclient.so``. Pointing at the game's local
      copy creates a circular reference — the library's fallback logic
      finds the "real" library at ``$HOME/.steam/sdk64/steamclient.so``,
      follows the symlink, and finds itself. That was a bug in an
      earlier iteration of this helper; do NOT reintroduce it.

    Requires the Palworld recipe to pin ``HOME`` to ``install_dir`` so
    ``$HOME/.steam/`` lands under install_dir (writable by gamesrv,
    scoped per-server, no /home/gamesrv pollution).
    """
    from pathlib import Path
    import shutil as _shutil

    install_dir = Path(install_dir)

    # Find a SteamCMD-provided steamclient.so to symlink to. Order of
    # preference — SteamCMD's runtime cache first (freshest), then the
    # copy Palworld ships in linux64/ (which is the same library, just
    # installed to a different path by Palworld's SteamCMD invocation).
    # We DO NOT accept Pal/Binaries/Linux/steamclient.so as a target
    # because that's the server-mode shim library and self-referential
    # from an sdk64/ symlink.
    sdk64_candidates = [
        install_dir / ".local" / "share" / "Steam" / "steamcmd" / "linux64" / "steamclient.so",
        install_dir / "linux64" / "steamclient.so",
    ]
    sdk32_candidates = [
        install_dir / ".local" / "share" / "Steam" / "steamcmd" / "linux32" / "steamclient.so",
        install_dir / "linux32" / "steamclient.so",
    ]

    def _pick_target(candidates: list[Path]) -> Path | None:
        for c in candidates:
            if c.exists() and c.is_file():
                return c
        return None

    target64 = _pick_target(sdk64_candidates)
    target32 = _pick_target(sdk32_candidates)

    msgs: list[str] = []

    if target64 is None:
        msgs.append(
            "WARNING (Palworld): could not find any SteamCMD-provided "
            f"steamclient.so under {install_dir}. Palworld will hang at "
            "SteamAPI_Init. Re-run Install so SteamCMD populates its runtime cache."
        )
        return msgs

    def _install_symlink(sdk_dir_name: str, target: Path | None, arch: str) -> None:
        if target is None:
            msgs.append(f"NOTE (Palworld): no {arch} steamclient.so found — skipping .steam/{sdk_dir_name}/")
            return
        sdk_dir = install_dir / ".steam" / sdk_dir_name
        try:
            sdk_dir.mkdir(parents=True, exist_ok=True)
        except OSError as e:
            msgs.append(
                f"WARNING (Palworld): could not create {sdk_dir} ({e}). "
                "Steam runtime may fail — fix ownership on install_dir."
            )
            return

        link = sdk_dir / "steamclient.so"
        # Reject reinstating a circular symlink from any earlier bad state.
        BANNED_TARGETS = {
            install_dir / "Pal" / "Binaries" / "Linux" / "steamclient.so",
        }
        if target in BANNED_TARGETS:
            msgs.append(
                f"WARNING (Palworld): refused to symlink {link} at {target} — "
                "that's the game's own server-mode shim and creates a circular "
                "reference. Skipping — Install needs to re-run SteamCMD."
            )
            return

        # Idempotent: if link exists and already points at the right file,
        # leave it. Otherwise replace with the fresh target.
        try:
            if link.is_symlink() or link.exists():
                current = link.resolve(strict=False)
                if current == target.resolve(strict=False):
                    msgs.append(
                        f"post-install (Palworld): .steam/{sdk_dir_name}/steamclient.so "
                        f"already points at {target.name} — Steam runtime OK"
                    )
                    return
                try:
                    link.unlink()
                except OSError:
                    pass
        except OSError:
            pass

        try:
            link.symlink_to(target)
            msgs.append(
                f"post-install (Palworld): linked .steam/{sdk_dir_name}/steamclient.so "
                f"-> {target.relative_to(install_dir)} (fixes SteamAPI_Init hang)"
            )
        except OSError as e:
            # Fall back to a copy if symlink is disallowed (rare on
            # unpriv LXCs). Copy has the same effect at load time.
            try:
                _shutil.copy2(target, link)
                msgs.append(
                    f"post-install (Palworld): copied {target.name} → "
                    f".steam/{sdk_dir_name}/ (symlink failed: {e})"
                )
            except OSError as e2:
                msgs.append(
                    f"WARNING (Palworld): could not install Steam runtime shim ({e2}). "
                    "Game will hang at SteamAPI_Init."
                )

    _install_symlink("sdk64", target64, "64-bit")
    _install_symlink("sdk32", target32, "32-bit")

    # Some Palworld builds also check for $HOME/.steam/steam/. Create an
    # empty directory so any getcwd/stat check succeeds without the
    # heavy state a real Steam Client would put there. Best effort.
    try:
        (install_dir / ".steam" / "steam").mkdir(parents=True, exist_ok=True)
    except OSError:
        pass

    return msgs


def _apply_satisfactory_autoload(sd, install_dir, world_dir) -> list[str]:
    """Write AutoLoadSessionName into Satisfactory's Game.ini."""
    from pathlib import Path
    saves_dir = Path(world_dir) / "SaveGames" / "server"
    sav_files = sorted(saves_dir.glob("*.sav"),
                       key=lambda p: p.stat().st_mtime, reverse=True) \
        if saves_dir.is_dir() else []

    ini_dir = Path(install_dir) / "FactoryGame" / "Saved" / "Config" / "LinuxServer"
    ini_dir.mkdir(parents=True, exist_ok=True)
    ini_path = ini_dir / "Game.ini"

    if not sav_files:
        # No save uploaded yet — make sure Game.ini isn't stale from a
        # previous install pointing at a deleted save.
        if ini_path.exists():
            existing = ini_path.read_text(encoding="utf-8", errors="replace")
            if "AutoLoadSessionName=" in existing:
                # Leave the operator's file alone but flag it.
                return [
                    "post-install: no .sav in world_dir/SaveGames/server/; "
                    f"existing {ini_path.name} has AutoLoadSessionName — verify "
                    "the referenced save still exists"
                ]
        return [
            "post-install: no .sav in world_dir/SaveGames/server/ — upload one "
            "via the Files tab (area=world_dir, path=SaveGames/server) and "
            "re-run Install to auto-configure AutoLoadSessionName"
        ]

    # Session name is the .sav filename without extension.
    session_name = sav_files[0].stem

    desired = (
        "; Auto-generated by gamesrv on Install/Update. Points the dedicated\n"
        "; server at the newest .sav under world_dir/SaveGames/server/. Re-run\n"
        "; Install after uploading a different save to update this file.\n"
        "[/Script/FactoryGame.FGServerSubsystem]\n"
        f"AutoLoadSessionName={session_name}\n"
    )

    # Only rewrite if the current file is missing/older; if the operator
    # hand-edited an operator marker we leave it alone.
    if ini_path.exists():
        current = ini_path.read_text(encoding="utf-8", errors="replace")
        if "MANAGED=false" in current:
            return [f"post-install: {ini_path.name} has MANAGED=false — leaving hand-edited file alone"]
        if current == desired:
            return [f"post-install: {ini_path.name} already up to date (AutoLoadSessionName={session_name})"]

    ini_path.write_text(desired, encoding="utf-8")
    return [
        f"post-install: wrote {ini_path} (AutoLoadSessionName={session_name})",
        f"           picked newest of {len(sav_files)} .sav file(s) in {saves_dir}",
    ]
