"""SteamCMD-based dedicated servers (Palworld, Valheim, ARK, etc.).

We shell out to `steamcmd` to install/update. The user provides steam_app_id
in the server YAML (Palworld = 2394010). Anonymous login covers most
free-to-host dedicated servers.

Palworld notes (baked into the default start.sh):
  - Binary lives at Pal/Binaries/Linux/PalServer-Linux-Shipping
  - Also ships a top-level PalServer.sh wrapper — we call that.
  - Save data lives in Pal/Saved — we symlink Saved -> world_dir so the
    NFS bind mount holds saves.
"""
from __future__ import annotations

import shutil
import subprocess

from .base import TypeHandler


_START_TEMPLATE = """#!/usr/bin/env bash
# Generated by gamesrv manager. Runs a SteamCMD-installed dedicated server
# inside tmux so the console channel + graceful stop work.
set -euo pipefail
cd "$(dirname "$0")"

SESSION="gs-{name}"
BIN="{run_cmd}"

if ! command -v tmux >/dev/null; then
  echo "ERROR: tmux is required (apt install tmux)" >&2
  exit 1
fi

tmux kill-session -t "$SESSION" 2>/dev/null || true

# Foreground tmux so systemd tracks PID (see minecraft_java.py for why).
exec tmux new-session -s "$SESSION" -n game "$BIN"
"""


_STOP_TEMPLATE = """#!/usr/bin/env bash
# Most SteamCMD servers respond to SIGINT for a clean shutdown. tmux
# send-keys C-c then wait; systemd will hard-kill if we exceed the unit
# TimeoutStopSec.
set -euo pipefail
SESSION="gs-{name}"
if tmux has-session -t "$SESSION" 2>/dev/null; then
  tmux send-keys -t "$SESSION" C-c || true
  for _ in $(seq 1 60); do
    tmux has-session -t "$SESSION" 2>/dev/null || exit 0
    sleep 1
  done
fi
"""


# --- built-in run-command recipes per known app id ---------------------------
# Extend this dict when adding a new SteamCMD game.
_APP_RECIPES: dict[int, dict] = {
    2394010: {  # Palworld dedicated
        "name": "palworld",
        "run": "./PalServer.sh -port={port} -useperfthreads -NoAsyncLoadingThread -UseMultithreadForDS",
        "saves_rel": "Pal/Saved",
    },
    896660: {   # Valheim dedicated
        "name": "valheim",
        "run": "./valheim_server.x86_64 -name '{name}' -port {port} -world 'Dedicated' -password 'CHANGE_ME_IN_START_SH' -public 0",
        "saves_rel": ".config/unity3d/IronGate/Valheim",
    },
}


class SteamCmdHandler(TypeHandler):
    def install(self) -> list[str]:
        if not self.sd.steam_app_id:
            raise ValueError("steamcmd type requires steam_app_id in the definition")
        self.ensure_dirs()
        msgs: list[str] = []

        steamcmd = shutil.which("steamcmd")
        if not steamcmd:
            raise RuntimeError("steamcmd not installed — run: sudo apt install steamcmd (or see docs)")

        # Anonymous install/update. +force_install_dir must come BEFORE +login.
        cmd = [
            steamcmd,
            "+@sSteamCmdForcePlatformType", "linux",
            "+force_install_dir", str(self.install_dir),
            "+login", "anonymous",
            "+app_update", str(self.sd.steam_app_id),
        ]
        if self.sd.steam_beta:
            cmd += ["-beta", self.sd.steam_beta]
        cmd += ["validate", "+quit"]

        msgs.append(f"running: {' '.join(cmd)}")
        r = subprocess.run(cmd, capture_output=True, text=True, timeout=60 * 60)
        # SteamCMD prints a lot; keep the last ~30 lines for the UI response.
        tail = "\n".join((r.stdout + r.stderr).splitlines()[-30:])
        msgs.append(tail)
        if r.returncode != 0:
            raise RuntimeError(f"steamcmd failed (exit {r.returncode}):\n{tail}")

        recipe = _APP_RECIPES.get(self.sd.steam_app_id, {
            "name": "generic",
            "run": self.sd.start_cmd or "./start.sh",
            "saves_rel": None,
        })

        run_cmd = recipe["run"].format(name=self.sd.name, port=self.sd.port)
        self.write_script(
            "start.sh",
            _START_TEMPLATE.format(name=self.sd.name, run_cmd=run_cmd),
        )
        self.write_script("stop.sh", _STOP_TEMPLATE.format(name=self.sd.name))
        msgs.append(f"wrote {self.install_dir/'start.sh'}")

        # Symlink the game's saves dir onto the NFS-backed world_dir.
        if recipe["saves_rel"]:
            saves = self.install_dir / recipe["saves_rel"]
            saves.parent.mkdir(parents=True, exist_ok=True)
            if saves.is_symlink() or saves.exists():
                if saves.is_symlink():
                    saves.unlink()
                elif saves.is_dir() and not any(saves.iterdir()):
                    saves.rmdir()
                else:
                    msgs.append(
                        f"WARNING: {saves} exists and is not a symlink; leaving alone. "
                        "Move its contents to world_dir and delete it, then re-run install."
                    )
            if not saves.exists():
                saves.symlink_to(self.world_dir)
                msgs.append(f"symlinked {saves} -> {self.world_dir}")

        env_values = {"GAME_PORT": str(self.sd.port), "MEMORY_MB": str(self.sd.memory_mb)}
        env_values.update(self.sd.extra_env)
        self.write_env_file(env_values)
        msgs.append(f"wrote {self.install_dir/'server.env'}")

        return msgs

    def update(self) -> list[str]:
        # For SteamCMD games, update == re-run install (validates + patches).
        return self.install()
